name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Installing wasm
      run: rustup target install wasm32-unknown-unknown
    - name: Installing wasm cli
      run: cargo install -f wasm-bindgen-cli
    - name: Build
      run: cargo build --target wasm32-unknown-unknown
    - name: Building wasm
      run: wasm-bindgen --out-dir ./out/ --target web ./target/wasm32-unknown-unknown/debug/combobox-game.wasm
    - name: Create build folder
      run: mkdir build && xcopy .\assets .\build\assets /E/C/I && xcopy .\index.html .\build && xcopy .\out .\build\out /E/C/I
    - name: Push wasm build artifacts to git hub pages branch
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        MESSAGE: "Master build update"
